import DashboardLayout from "@/components/DashboardLayout";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Activity, ArrowUpRight, BarChart3, Database, RefreshCw, ShieldAlert, Sparkles, TrendingUp, Waves } from "lucide-react";
import { useMemo, useState } from "react";
import { Link } from "wouter";
import { trpc } from "@/lib/trpc";
import { rankStocks } from "@shared/ranking";
import { groupHistoryRows } from "@shared/history";
import { filterZones, sortDirectionalZones, type ConfidenceFilter, type DirectionFilter } from "@shared/zoneFilters";
import { alertNavigationTarget, filterAlertHistoryRows } from "@shared/alertHistory";
import { AlertHistoryControls } from "@/components/AlertHistoryControls";
import { useAuth } from "@/_core/hooks/useAuth";
import { ResponsiveContainer, AreaChart, Area, XAxis, YAxis, Tooltip, BarChart, Bar } from "recharts";

const navItems = ["Overview", "History", "Stock detail", "Alert history", "Methodology"];

function confidenceClass(value: string) {
  return value === "High" ? "border-emerald-400/20 bg-emerald-400/10 text-emerald-300" : value === "Medium" ? "border-amber-400/20 bg-amber-400/10 text-amber-300" : "border-slate-400/20 bg-slate-400/10 text-slate-300";
}

function directionClass(value: string) {
  return value === "Potential Accumulation" ? "border-cyan-400/20 bg-cyan-400/10 text-cyan-200" : value === "Potential Distribution" ? "border-rose-400/20 bg-rose-400/10 text-rose-200" : "border-slate-400/20 bg-slate-400/10 text-slate-300";
}

function directionLabel(value?: string) {
  return value ?? "No direction";
}

function alertStatusClass(value?: string) {
  return value === "sent" ? "border-emerald-400/20 bg-emerald-400/10 text-emerald-200" : value === "failed" ? "border-rose-400/20 bg-rose-400/10 text-rose-200" : "border-slate-400/20 bg-slate-400/10 text-slate-300";
}

export default function Home() {
  const [activeTab, setActiveTab] = useState("Overview");
  const [selectedSymbol, setSelectedSymbol] = useState<string | null>(null);
  const [directionFilter, setDirectionFilter] = useState<DirectionFilter>("All");
  const [confidenceFilter, setConfidenceFilter] = useState<ConfidenceFilter>("All");
  const { user } = useAuth();
  const snapshot = trpc.dashboard.snapshot.useQuery(undefined, { refetchInterval: 5 * 60 * 1000, refetchIntervalInBackground: false, staleTime: 60 * 1000 });
  const history = trpc.dashboard.history.useQuery();
  const alertHistory = trpc.dashboard.alertHistory.useQuery();
  const detail = trpc.dashboard.stock.useQuery({ symbol: selectedSymbol ?? "" }, { enabled: Boolean(selectedSymbol) });
  const refreshAll = () => {
    void snapshot.refetch();
    void history.refetch();
    void alertHistory.refetch();
    if (selectedSymbol) void detail.refetch();
  };
  const isRefreshing = snapshot.isFetching || history.isFetching || alertHistory.isFetching || detail.isFetching;
  const stocks = snapshot.data?.stocks ?? [];
  const zones = snapshot.data?.zones ?? [];
  const hasRenderableZones = !snapshot.isError && zones.length > 0;
  const filteredZones = useMemo(() => sortDirectionalZones(filterZones(zones, directionFilter, confidenceFilter)), [confidenceFilter, directionFilter, zones]);
  const accumulationAlerts = useMemo(() => filteredZones.filter((entry: any) => entry.zone.direction === "Potential Accumulation" && entry.zone.confidence === "High"), [filteredZones]);
  const alertStatus = snapshot.data?.alertStatus ?? "not_run";
  const dateFormat = { day: "2-digit", month: "short", year: "numeric" } as const;
  const todayDate = new Date().toLocaleDateString("en-GB", dateFormat);
  const latestDate = snapshot.data?.latestDate ? new Date(snapshot.data.latestDate).toLocaleDateString("en-GB", dateFormat) : "Awaiting first run";
  const sourceStatus = snapshot.data?.sourceStatus ?? "no-data";
  const sourceStatusLabel = sourceStatus === "stale" ? "stale — awaiting newer close" : sourceStatus === "partial" ? "partial — some symbols unavailable" : sourceStatus === "current" ? "current" : "no verified data";
  const rankedStocks = useMemo(() => rankStocks(stocks, zones), [stocks, zones]);
  const heatmap = useMemo(() => rankedStocks.map((item: any) => ({ symbol: item.instrument.symbol.replace(".EGX", ""), volume: item.bar.volume })), [rankedStocks]);
  const historyRows = useMemo(() => groupHistoryRows(history.data?.rows ?? [], history.data?.latestDate ?? null, history.data?.previousDate ?? null), [history.data]);

  return <DashboardLayout>
    <div className="min-h-screen bg-[#071018] text-slate-100 -m-4 p-5 lg:p-8">
      <header className="mx-auto max-w-[1500px] flex flex-col gap-6 border-b border-white/10 pb-7 lg:flex-row lg:items-end lg:justify-between">
        <div>
          <div className="mb-5 flex items-center gap-3 text-xs font-medium uppercase tracking-[0.24em] text-cyan-300"><span className="h-2 w-2 rounded-full bg-cyan-300 shadow-[0_0_18px_#67e8f9]" /> Market intelligence workspace</div>
          <h1 className="text-3xl font-semibold tracking-tight text-white lg:text-5xl">EGX30 <span className="text-slate-500">/</span> Volume Zones</h1>
          <p className="mt-3 max-w-2xl text-sm leading-6 text-slate-400">A daily, evidence-led view of price acceptance and unusual volume across the Egyptian Exchange.</p>
        </div>
        <div className="flex flex-wrap items-center gap-3">
          <select aria-label="Filter directional zones" value={directionFilter} onChange={e => setDirectionFilter(e.target.value as typeof directionFilter)} className="rounded-lg border border-white/10 bg-white/[0.04] px-3 py-2 text-xs text-slate-200"><option value="All">All directions</option><option value="Potential Accumulation">Potential Accumulation</option><option value="Potential Distribution">Potential Distribution</option><option value="Neutral">Neutral</option></select><select aria-label="Filter confidence levels" value={confidenceFilter} onChange={e => setConfidenceFilter(e.target.value as typeof confidenceFilter)} className="rounded-lg border border-white/10 bg-white/[0.04] px-3 py-2 text-xs text-slate-200"><option value="All">All confidence</option><option value="High">High confidence</option><option value="Medium">Medium confidence</option><option value="Low">Low confidence</option></select>
          <div className="rounded-full border border-white/10 bg-white/[0.04] px-4 py-2 text-xs text-slate-400"><span>Today</span><span className="ml-2 font-medium text-slate-200">{todayDate}</span><span className="mx-2 text-slate-600">•</span><span>Last verified close</span><span className="ml-2 font-medium text-slate-200">{latestDate}</span><span className="mx-2 text-slate-600">•</span><span>Source</span><span className={`ml-2 font-medium ${sourceStatus === "stale" ? "text-amber-300" : sourceStatus === "current" ? "text-emerald-300" : "text-slate-400"}`}>{sourceStatusLabel}</span><span className="mx-2 text-slate-600">•</span><span>Active window</span><span className="ml-2 font-medium text-slate-200">{snapshot.data?.activeZoneWindowSessions ?? 10} sessions</span></div>
          <Button onClick={refreshAll} disabled={isRefreshing} variant="outline" className="border-white/10 bg-white/[0.04] text-slate-200 hover:bg-white/[0.08]"><RefreshCw className={`mr-2 h-4 w-4 ${isRefreshing ? "animate-spin" : ""}`} />{isRefreshing ? "Refreshing…" : "Refresh"}</Button>
        </div>
      </header>

      <main className="mx-auto max-w-[1500px]">
        <nav className="flex gap-7 border-b border-white/10 pt-5 text-sm text-slate-500">
          {navItems.map(tab => <button key={tab} onClick={() => setActiveTab(tab)} className={`relative pb-4 transition-colors ${activeTab === tab ? "text-cyan-300" : "hover:text-slate-200"}`}>{tab}{activeTab === tab && <span className="absolute inset-x-0 -bottom-px h-px bg-cyan-300" />}</button>)}
          {user && <Link href="/settings" className="ml-auto pb-4 text-slate-500 hover:text-slate-200">Configure source →</Link>}
        </nav>

        {activeTab === "Overview" && <>
          {snapshot.isError && <div className="mb-5 rounded-xl border border-rose-300/20 bg-rose-300/[0.06] p-4 text-sm text-rose-200">Unable to load the latest market snapshot. Check the provider connection and try again.</div>}
          {snapshot.isLoading && <LoadingBanner label="Fetching the latest verified close and analysis state" /> }
          <section className="grid gap-4 py-7 sm:grid-cols-2 xl:grid-cols-4">
            <MetricCard label="Tracked universe" value={stocks.length ? `${stocks.length}` : "—"} suffix={stocks.length ? "stocks" : "no data"} icon={<Database />} tone="cyan" />
            <MetricCard label="Potential zones" value={stocks.length ? `${zones.length}` : "—"} suffix={stocks.length ? "identified" : "no data"} icon={<Waves />} tone="violet" />
            <MetricCard label="High confidence" value={stocks.length ? `${zones.filter((z: any) => z.zone.confidence === "High").length}` : "—"} suffix={stocks.length ? "zones" : "no data"} icon={<Sparkles />} tone="emerald" />
            <MetricCard label="Run status" value={snapshot.isError ? "Error" : snapshot.isLoading ? "Syncing" : sourceStatus === "stale" ? "Source stale" : sourceStatus === "partial" ? "Partial" : latestDate === "Awaiting first run" ? "Setup" : "Ready"} suffix="daily close" icon={<Activity />} tone="amber" />
          </section>

          <Card className="mb-5 border-cyan-300/20 bg-cyan-300/[0.05] text-white"><CardHeader className="flex flex-row items-center justify-between border-b border-cyan-300/10 pb-4"><div><CardTitle className="text-base font-medium">Accumulation watch</CardTitle><p className="mt-1 text-xs text-slate-400">High-confidence potential accumulation zones from the latest verified close</p></div><div className="flex items-center gap-2"><Badge className={alertStatusClass(alertStatus)}>Alert {alertStatus === "not_run" ? "not run" : alertStatus}</Badge>{snapshot.data?.alertCount ? <span className="text-xs text-slate-500">{snapshot.data.alertCount} sent candidate{snapshot.data.alertCount === 1 ? "" : "s"}</span> : null}<Sparkles className="h-5 w-5 text-cyan-300" /></div></CardHeader><CardContent className="pt-4">{accumulationAlerts.length ? <div className="grid gap-3 md:grid-cols-3">{accumulationAlerts.slice(0, 6).map((entry: any) => <div key={entry.zone.id} className="rounded-xl border border-cyan-300/15 bg-black/10 p-4"><div className="flex items-center justify-between"><span className="font-medium">{entry.instrument.symbol.replace(".EGX", "")}</span><Badge className="border-cyan-400/20 bg-cyan-400/10 text-cyan-200">High</Badge></div><p className="mt-3 font-mono text-sm text-cyan-100">{entry.zone.lowerPrice.toFixed(2)} — {entry.zone.upperPrice.toFixed(2)}</p><p className="mt-2 text-xs text-slate-500">Strength {entry.zone.totalScore}/100 · volume {entry.zone.volumeRatio.toFixed(2)}x</p></div>)}</div> : <p className="text-sm text-slate-500">No high-confidence potential accumulation zone is available for this verified close.</p>}</CardContent></Card>

          <section className="grid gap-5 xl:grid-cols-[1.6fr_1fr]">
            <Card className="border-white/10 bg-white/[0.035] text-white shadow-2xl shadow-black/20">
              <CardHeader className="flex flex-row items-start justify-between border-b border-white/10 pb-5"><div><CardTitle className="text-base font-medium">Volume activity map</CardTitle><p className="mt-1 text-xs text-slate-500">Relative daily volume across tracked instruments</p></div><BarChart3 className="h-5 w-5 text-cyan-300" /></CardHeader>
              <CardContent className="pt-5">{heatmap.length ? <Heatmap data={heatmap} /> : <div className="h-[280px]"><EmptyChart title="Your first market map is one close away" body="The free daily source will populate this view after the next close; coverage can vary by symbol." /></div>}</CardContent>
            </Card>
            <Card className="border-white/10 bg-white/[0.035] text-white shadow-2xl shadow-black/20"><CardHeader className="border-b border-white/10 pb-5"><CardTitle className="text-base font-medium">Signal quality</CardTitle><p className="mt-1 text-xs text-slate-500">How zones are classified</p></CardHeader><CardContent className="space-y-5 pt-6"><SignalRow color="bg-emerald-300" label="High" text="Strong volume + tight acceptance" /><SignalRow color="bg-amber-300" label="Medium" text="Two of three conditions align" /><SignalRow color="bg-slate-400" label="Low" text="Early or weaker evidence" /><div className="border-t border-white/10 pt-4"><p className="mb-3 text-xs uppercase tracking-wider text-slate-500">Directional hypothesis</p><div className="flex flex-wrap gap-2"><Badge className={directionClass("Potential Accumulation")}>Potential Accumulation</Badge><Badge className={directionClass("Potential Distribution")}>Potential Distribution</Badge><Badge className={directionClass("Neutral")}>Neutral</Badge></div><p className="mt-3 text-xs leading-5 text-slate-500">Direction is inferred from daily OHLCV evidence and is not a buy or sell signal.</p></div><div className="rounded-xl border border-amber-300/15 bg-amber-300/[0.06] p-4 text-xs leading-5 text-amber-100/70"><ShieldAlert className="mb-2 h-4 w-4 text-amber-300" />All outputs are analytical observations, not an investment recommendation.</div></CardContent></Card>
          </section>

          <section className="mt-5 grid gap-5 xl:grid-cols-[1.5fr_1fr]">
            <Card className="border-white/10 bg-white/[0.035] text-white"><CardHeader className="flex flex-row items-center justify-between border-b border-white/10 pb-5"><div><CardTitle className="text-base font-medium">Tracked stocks</CardTitle><p className="mt-1 text-xs text-slate-500">Priority: Potential Accumulation first, then High / Medium / Low confidence; Strength Score breaks ties. Confirmation is excluded from the initial rank</p></div><TrendingUp className="h-5 w-5 text-violet-300" /></CardHeader><CardContent className="p-0">{rankedStocks.length ? <div className="divide-y divide-white/5">{rankedStocks.map((item: any) => <button onClick={() => setSelectedSymbol(item.instrument.symbol)} key={item.instrument.symbol} className="flex w-full items-center justify-between px-6 py-4 text-left transition-colors hover:bg-white/[0.04]"><div><div className="flex items-center gap-3"><span className="flex h-7 w-7 items-center justify-center rounded-full bg-cyan-300/10 text-xs font-semibold text-cyan-200">{rankedStocks.indexOf(item) + 1}</span><div><p className="font-medium text-slate-100">{item.instrument.symbol.replace(".EGX", "")}</p><div className="mt-1 flex flex-wrap items-center gap-2"><p className="text-xs text-slate-500">{item.instrument.name}</p>{item.bestZone && <><Badge className={directionClass(item.bestZone.direction ?? "Neutral")}>{directionLabel(item.bestZone.direction)}</Badge><Badge className={confidenceClass(item.bestZone.confidence)}>{item.bestZone.confidence}</Badge></>}</div></div></div></div><div className="text-right"><p className="font-mono text-sm text-slate-200">{item.bar.low.toFixed(2)} — {item.bar.high.toFixed(2)}</p><p className="mt-1 text-xs text-cyan-300">Strength {item.strengthScore}/100 · {Number(item.bar.volume).toLocaleString()} volume</p></div><ArrowUpRight className="ml-4 h-4 w-4 text-slate-600" /></button>)}</div> : <EmptyState />}</CardContent></Card>
            <Card className="border-white/10 bg-white/[0.035] text-white"><CardHeader className="border-b border-white/10 pb-5"><CardTitle className="text-base font-medium">Directional zones</CardTitle><p className="mt-1 text-xs text-slate-500">Ordered: Potential Accumulation → Potential Distribution → Neutral; confidence and zone score within each group</p></CardHeader><CardContent className="space-y-3 pt-5">{!hasRenderableZones ? <EmptyState compact /> : filteredZones.length ? filteredZones.slice(0, 5).map((entry: any) => <div key={entry.zone.id} className="rounded-xl border border-white/10 bg-black/10 p-4"><div className="flex items-center justify-between"><div className="flex flex-wrap items-center gap-2"><span className="font-medium">{entry.instrument.symbol.replace(".EGX", "")}</span><Badge className={directionClass(entry.zone.direction ?? "Neutral")}>{directionLabel(entry.zone.direction)}</Badge><Badge className={confidenceClass(entry.zone.confidence)}>{entry.zone.confidence}</Badge></div></div><p className="mt-3 font-mono text-sm text-cyan-200">{entry.zone.lowerPrice.toFixed(2)} — {entry.zone.upperPrice.toFixed(2)}</p><p className="mt-2 text-xs leading-5 text-slate-500">{entry.zone.explanation}</p></div>) : <div className="rounded-xl border border-dashed border-white/10 p-8 text-center text-sm text-slate-500">No zones match the selected direction filter.</div>}</CardContent></Card>
          </section>
        </>}

        {activeTab === "History" && <HistoryView history={history.data} rows={historyRows} isLoading={history.isLoading} detail={detail.data} selectedSymbol={selectedSymbol} setSelectedSymbol={setSelectedSymbol} symbols={rankedStocks} />}
        {activeTab === "Stock detail" && <StockDetail detail={detail.data} isLoading={detail.isLoading} selectedSymbol={selectedSymbol} setSelectedSymbol={setSelectedSymbol} symbols={rankedStocks} />}
        {activeTab === "Alert history" && <AlertHistoryView rows={alertHistory.data} isLoading={alertHistory.isLoading} isError={alertHistory.isError} onOpenSymbol={(symbol) => { setSelectedSymbol(alertNavigationTarget(symbol)); setActiveTab("Stock detail"); }} />}
        {activeTab === "Methodology" && <Methodology />}
      </main>
    </div>
  </DashboardLayout>;
}

function MetricCard({ label, value, suffix, icon, tone }: any) { const colors: any = { cyan: "text-cyan-300", violet: "text-violet-300", emerald: "text-emerald-300", amber: "text-amber-300" }; return <Card className="border-white/10 bg-white/[0.035] text-white"><CardContent className="p-5"><div className="flex items-center justify-between"><p className="text-xs uppercase tracking-[0.16em] text-slate-500">{label}</p><span className={colors[tone]}>{icon}</span></div><div className="mt-5 flex items-baseline gap-2"><span className="text-3xl font-semibold tracking-tight">{value}</span><span className="text-xs text-slate-500">{suffix}</span></div></CardContent></Card> }
function SignalRow({ color, label, text }: any) { return <div className="flex items-center gap-3"><span className={`h-2.5 w-2.5 rounded-full ${color}`} /><div><p className="text-sm text-slate-200">{label}</p><p className="text-xs text-slate-500">{text}</p></div></div> }
function LoadingBanner({ label }: { label: string }) { return <div className="mb-5 flex items-center gap-3 rounded-xl border border-cyan-300/15 bg-cyan-300/[0.05] p-4 text-sm text-cyan-100"><span className="loading-orbit" aria-hidden="true"><span /></span><span>{label}<span className="loading-dots" aria-hidden="true">...</span></span></div> }
function LoadingPanel({ label }: { label: string }) { return <div className="flex min-h-[230px] flex-col items-center justify-center rounded-xl border border-dashed border-cyan-300/15 bg-cyan-300/[0.025] text-center"><span className="loading-orbit loading-orbit-lg mb-5" aria-hidden="true"><span /></span><p className="text-sm text-slate-300">{label}</p><p className="mt-2 max-w-xs text-xs leading-5 text-slate-500">Only verified market data will appear when the source responds.</p></div> }
function EmptyChart({ title, body }: any) { return <div className="flex h-full flex-col items-center justify-center rounded-xl border border-dashed border-white/10 bg-black/10 text-center"><BarChart3 className="mb-4 h-8 w-8 text-slate-600" /><p className="text-sm text-slate-300">{title}</p><p className="mt-2 max-w-xs text-xs leading-5 text-slate-500">{body}</p></div> }
function EmptyState({ compact = false }: { compact?: boolean }) { return <div className={`flex flex-col items-center justify-center text-center ${compact ? "py-12" : "min-h-[230px] p-8"}`}><Database className="mb-3 h-7 w-7 text-slate-600" /><p className="text-sm text-slate-300">No market data yet</p><p className="mt-2 max-w-xs text-xs leading-5 text-slate-500">The free daily source will populate the dashboard after the next scheduled close.</p></div> }
function Heatmap({ data }: { data: { symbol: string; volume: number }[] }) { const max = Math.max(...data.map(item => item.volume), 1); return <div className="grid grid-cols-3 gap-2 sm:grid-cols-5 lg:grid-cols-6">{data.map(item => { const intensity = Math.max(0.12, item.volume / max); return <div key={item.symbol} className="rounded-xl border border-white/10 p-3" style={{ background: `rgba(103,232,249,${intensity * 0.55})` }}><p className="font-mono text-xs text-slate-100">{item.symbol}</p><p className="mt-3 text-[10px] text-slate-300">{Number(item.volume).toLocaleString()}</p></div> })}</div> }
function CandleChart({ bars }: { bars: any[] }) { const recent = bars.slice(-24); const max = Math.max(...recent.map(bar => Number(bar.high)), 1); const min = Math.min(...recent.map(bar => Number(bar.low)), 0); return <div className="grid grid-cols-12 items-end gap-2 rounded-xl border border-white/10 bg-black/10 p-5" style={{ height: 360 }}>{recent.length ? recent.map((bar, index) => { const open = Number(bar.open), close = Number(bar.close), high = Number(bar.high), low = Number(bar.low); const scale = (value: number) => ((value - min) / Math.max(max - min, 1)) * 270; const rising = close >= open; return <div key={index} className="relative flex h-full flex-col items-center justify-end"><div className="absolute bottom-0 w-full rounded-t bg-cyan-300/10" style={{ height: `${Math.max(8, Number(bar.volume) / Math.max(...recent.map((item: any) => Number(item.volume)), 1) * 70)}px` }} /><div className="absolute w-px bg-slate-300/60" style={{ bottom: scale(low), height: Math.max(8, scale(high) - scale(low)) }} /><div className={`absolute w-3 rounded-sm ${rising ? "bg-emerald-300" : "bg-rose-300"}`} style={{ bottom: scale(Math.min(open, close)), height: Math.max(4, Math.abs(scale(close) - scale(open))) }} /></div> }) : <div className="col-span-12 flex items-center justify-center text-sm text-slate-500">No candle data yet.</div>}</div> }
function HistoryView({ history, rows, isLoading, detail, selectedSymbol, setSelectedSymbol, symbols }: any) {
  const sortedRows = [...rows].sort((a, b) => (b.comparison.closeChangePct ?? -Infinity) - (a.comparison.closeChangePct ?? -Infinity));
  return <section className="space-y-5 py-7">
    <div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs uppercase tracking-[0.2em] text-cyan-300">Evidence timeline</p><h2 className="mt-2 text-2xl font-semibold">Daily comparison & long-term history</h2><p className="mt-2 text-sm text-slate-500">Only persisted daily bars are compared. Missing sessions remain explicit no data.</p></div><select aria-label="History instrument" value={selectedSymbol ?? ""} onChange={e => setSelectedSymbol(e.target.value || null)} className="rounded-lg border border-white/10 bg-white/[0.05] px-4 py-2 text-sm text-slate-200"><option value="">Choose tracked stock</option>{symbols.map((item: any) => <option key={item.instrument.symbol} value={item.instrument.symbol}>{item.instrument.symbol.replace(".EGX", "")}</option>)}</select></div>
    {isLoading ? <LoadingPanel label="Loading persisted daily history" /> : !history?.rows?.length ? <EmptyState /> : <>
      <Card className="border-white/10 bg-white/[0.035] text-white"><CardHeader className="border-b border-white/10 pb-5"><CardTitle className="text-base">Latest close versus previous session</CardTitle><p className="mt-1 text-xs text-slate-500">{history.latestDate ? new Date(history.latestDate).toLocaleDateString("en-GB") : "No data"} compared with {history.previousDate ? new Date(history.previousDate).toLocaleDateString("en-GB") : "No prior session"}</p></CardHeader><CardContent className="overflow-x-auto p-0"><table className="w-full min-w-[720px] text-sm"><thead className="text-left text-xs uppercase tracking-wider text-slate-500"><tr><th className="px-6 py-4">Rank</th><th className="px-6 py-4">Symbol</th><th className="px-6 py-4">Latest close</th><th className="px-6 py-4">Close change</th><th className="px-6 py-4">Volume change</th></tr></thead><tbody className="divide-y divide-white/5">{sortedRows.map((row: any, index: number) => <tr key={row.instrument.symbol} className="hover:bg-white/[0.03]"><td className="px-6 py-4 text-cyan-300">{index + 1}</td><td className="px-6 py-4 font-medium text-slate-100">{row.instrument.symbol.replace(".EGX", "")}</td><td className="px-6 py-4 font-mono text-slate-300">{row.current ? Number(row.current.close).toFixed(2) : "—"}</td><td className={`px-6 py-4 font-mono ${row.comparison.closeChangePct == null ? "text-slate-500" : row.comparison.closeChangePct >= 0 ? "text-emerald-300" : "text-rose-300"}`}>{row.comparison.closeChangePct == null ? "no data" : `${row.comparison.closeChangePct >= 0 ? "+" : ""}${row.comparison.closeChangePct.toFixed(2)}%`}</td><td className="px-6 py-4 font-mono text-slate-400">{row.comparison.volumeChangePct == null ? "no data" : `${row.comparison.volumeChangePct >= 0 ? "+" : ""}${row.comparison.volumeChangePct.toFixed(2)}%`}</td></tr>)}</tbody></table></CardContent></Card>
      <Card className="border-white/10 bg-white/[0.035] text-white"><CardHeader className="border-b border-white/10 pb-5"><CardTitle className="text-base">Long-term price and volume history</CardTitle><p className="mt-1 text-xs text-slate-500">Up to 90 persisted sessions for the selected instrument.</p></CardHeader><CardContent>{detail?.bars?.length ? <><CandleChart bars={detail.bars} /><div className="mt-4 flex justify-between text-xs text-slate-500"><span>First persisted session: {new Date(detail.bars[0].tradingDate).toLocaleDateString("en-GB")}</span><span>Latest persisted session: {new Date(detail.bars[detail.bars.length - 1].tradingDate).toLocaleDateString("en-GB")}</span></div></> : <EmptyChart title="Select an instrument" body="Choose a tracked EGX30 stock to inspect its persisted long-term history." />}</CardContent></Card>
    </>}
  </section>;
}

function AlertHistoryView({ rows, isLoading, isError, onOpenSymbol }: { rows?: any[]; isLoading: boolean; isError: boolean; onOpenSymbol: (symbol: string) => void }) {
  const [search, setSearch] = useState("");
  const filteredRows = filterAlertHistoryRows(rows ?? [], search);
  return <section className="space-y-5 py-7"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs uppercase tracking-[0.2em] text-cyan-300">Operational record</p><h2 className="mt-2 text-2xl font-semibold">Alert history</h2><p className="mt-2 text-sm text-slate-500">Only persisted analysis-run records are shown. No alert record is created when a run did not produce one.</p></div><AlertHistoryControls search={search} onSearch={setSearch} noMatches={false} details={[]} rowId={0} onOpenSymbol={onOpenSymbol} /></div>{isLoading ? <LoadingPanel label="Loading persisted alert history" /> : isError ? <div className="rounded-xl border border-rose-300/20 bg-rose-300/[0.06] p-5 text-sm text-rose-200">Unable to load alert history. No synthetic alert rows are shown.</div> : !rows?.length ? <EmptyState /> : !filteredRows.length ? <div className="rounded-xl border border-dashed border-white/10 p-10 text-center text-sm text-slate-500">No matching alert records for “{search}”. Search uses only persisted symbols and recorded price ranges.</div> : <Card className="border-white/10 bg-white/[0.035] text-white"><CardHeader className="border-b border-white/10 pb-5"><CardTitle className="text-base">Recent daily runs</CardTitle><p className="mt-1 text-xs text-slate-500">Last 30 persisted analysis runs</p></CardHeader><CardContent className="overflow-x-auto p-0"><table className="w-full min-w-[820px] text-sm"><thead className="text-left text-xs uppercase tracking-wider text-slate-500"><tr><th className="px-6 py-4">Run time</th><th className="px-6 py-4">Status</th><th className="px-6 py-4">Alert status</th><th className="px-6 py-4">Count</th><th className="px-6 py-4">Recorded details</th></tr></thead><tbody className="divide-y divide-white/5">{filteredRows.map((row: any) => { let details: string[] = []; try { details = row.alertDetails ? JSON.parse(row.alertDetails) : []; } catch { details = []; } return <tr key={row.id} className="align-top hover:bg-white/[0.03]"><td className="px-6 py-4 font-mono text-xs text-slate-300">{row.runDate ? new Date(row.runDate).toLocaleString("en-GB") : "no data"}</td><td className="px-6 py-4"><Badge className={row.status === "completed" ? "border-emerald-400/20 bg-emerald-400/10 text-emerald-200" : "border-rose-400/20 bg-rose-400/10 text-rose-200"}>{row.status}</Badge></td><td className="px-6 py-4"><Badge className={alertStatusClass(row.alertStatus)}>{row.alertStatus}</Badge>{row.alertError && <p className="mt-2 max-w-xs text-xs text-rose-300">{row.alertError}</p>}</td><td className="px-6 py-4 font-mono text-slate-300">{row.alertCount ?? 0}</td><td className="max-w-md px-6 py-4 text-xs leading-5 text-slate-400">{details.length ? <AlertHistoryControls search="" onSearch={() => undefined} noMatches={false} details={details} rowId={row.id} onOpenSymbol={onOpenSymbol} /> : "No alert details recorded"}</td></tr>})}</tbody></table></CardContent></Card>}</section>;
}

function ConfirmationRow({ confirmation }: { confirmation: any }) { return <div className="mt-3 grid grid-cols-3 gap-2">{([1, 3, 5] as const).map((session) => { const point = confirmation?.[session]; return <div key={session} className="rounded-lg bg-white/[0.04] p-2"><p className="text-[10px] uppercase tracking-wider text-slate-500">{session} session{session > 1 ? "s" : ""}</p><p className={`mt-1 text-xs ${point?.status === "Upward break" ? "text-emerald-300" : point?.status === "Downward break" ? "text-rose-300" : point ? "text-amber-200" : "text-slate-500"}`}>{point ? point.status : "No data"}</p>{point && <p className="mt-1 font-mono text-[10px] text-slate-500">{point.changeFromZoneMidPct >= 0 ? "+" : ""}{point.changeFromZoneMidPct.toFixed(2)}%</p>}</div> })}</div> }

function StockDetail({ detail, isLoading, selectedSymbol, setSelectedSymbol, symbols }: any) { return <section className="py-7"><div className="mb-5 flex flex-wrap items-center justify-between gap-3"><div><p className="text-xs uppercase tracking-[0.2em] text-cyan-300">Instrument detail</p><h2 className="mt-2 text-2xl font-semibold">{selectedSymbol ?? "Select a stock"}</h2></div><select value={selectedSymbol ?? ""} onChange={e => setSelectedSymbol(e.target.value || null)} className="rounded-lg border border-white/10 bg-white/[0.05] px-4 py-2 text-sm text-slate-200"><option value="">Choose tracked stock</option>{symbols.map((item: any) => <option key={item.instrument.symbol} value={item.instrument.symbol}>{item.instrument.symbol.replace(".EGX", "")}</option>)}</select></div>{isLoading ? <LoadingPanel label="Fetching verified price and volume history" /> : detail ? <div className="grid gap-5 xl:grid-cols-[1.6fr_1fr]"><Card className="border-white/10 bg-white/[0.035] text-white"><CardHeader><CardTitle className="text-base">Candlestick + volume profile</CardTitle></CardHeader><CardContent><CandleChart bars={detail.bars} /><div className="mt-4 flex gap-4 text-xs text-slate-500"><span><i className="mr-2 inline-block h-2 w-2 rounded-full bg-emerald-300" />Up close</span><span><i className="mr-2 inline-block h-2 w-2 rounded-full bg-rose-300" />Down close</span><span><i className="mr-2 inline-block h-2 w-2 rounded-sm bg-cyan-300/40" />Volume band</span></div></CardContent></Card><Card className="border-white/10 bg-white/[0.035] text-white"><CardHeader><CardTitle className="text-base">Potential zones</CardTitle></CardHeader><CardContent>{detail.zones?.length ? detail.zones.slice(0, 8).map((zone: any) => <div key={zone.id} className="mb-3 rounded-xl border border-white/10 p-4"><div className="flex justify-between"><div className="flex flex-wrap items-center gap-2"><span className="font-mono text-cyan-200">{zone.lowerPrice} — {zone.upperPrice}</span><span className="text-[10px] uppercase tracking-wider text-slate-500">{new Date(zone.tradingDate).toLocaleDateString("en-GB", { day: "2-digit", month: "short" })}</span><Badge className={directionClass(zone.direction ?? "Neutral")}>{directionLabel(zone.direction)}</Badge><Badge className={confidenceClass(zone.confidence)}>{zone.confidence}</Badge><Badge className={zone.lifecycleStatus === "historical" ? "border-white/10 bg-white/[0.06] text-slate-400" : "border-emerald-300/20 bg-emerald-300/[0.08] text-emerald-200"}>{zone.lifecycleStatus === "historical" ? "Historical" : "Active"}</Badge></div></div><p className="mt-2 text-xs text-slate-500">{zone.explanation}</p><ConfirmationRow confirmation={zone.confirmation} /></div>) : <EmptyState compact />}</CardContent></Card></div> : <EmptyChart title="Select an instrument" body="Choose a tracked EGX30 stock to inspect its historical price behavior and detected zones." />}</section> }
function Methodology() { return <section className="grid gap-5 py-7 lg:grid-cols-3"><Card className="border-white/10 bg-white/[0.035] text-white lg:col-span-2"><CardHeader><CardTitle>How the signal is formed</CardTitle></CardHeader><CardContent className="space-y-5 text-sm leading-7 text-slate-400"><p>The free mode compares daily OHLCV observations with the historical session baseline, measures repeated price acceptance, and checks relatively narrow daily ranges. It does not manufacture two-hour bars when genuine intraday data is unavailable.</p><p>The resulting composite score maps to exactly three confidence tiers: <strong className="text-emerald-300">High</strong>, <strong className="text-amber-300">Medium</strong>, or <strong className="text-slate-200">Low</strong>. These labels describe evidence strength, not expected returns.</p><p>Direction is classified conservatively from the close location inside the daily range, the preceding close, and elevated volume: <strong className="text-cyan-200">Potential Accumulation</strong>, <strong className="text-rose-200">Potential Distribution</strong>, or <strong className="text-slate-200">Neutral</strong>. The label is a hypothesis for review, not a buy or sell signal.</p><blockquote className="border-l-2 border-cyan-300 pl-4 text-slate-300">Analytical results are not an investment recommendation. Always validate data quality and perform independent research.</blockquote></CardContent></Card><Card className="border-white/10 bg-white/[0.035] text-white"><CardHeader><CardTitle>Daily cadence</CardTitle></CardHeader><CardContent className="space-y-4 text-sm text-slate-400"><div className="rounded-xl bg-white/[0.04] p-4"><p className="text-xs uppercase tracking-wider text-slate-500">Trigger</p><p className="mt-2 text-lg text-slate-100">14:30 Cairo</p></div><div className="rounded-xl bg-white/[0.04] p-4"><p className="text-xs uppercase tracking-wider text-slate-500">Output</p><p className="mt-2 text-slate-200">New daily close, zones and heat map</p></div></CardContent></Card></section> }
