import DashboardLayout from "@/components/DashboardLayout";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Badge } from "@/components/ui/badge";
import { Check, Eye, EyeOff, KeyRound, Save, ShieldCheck, Sparkles, Clock3 } from "lucide-react";
import { useEffect, useState } from "react";
import { Link } from "wouter";
import { trpc } from "@/lib/trpc";
import { defaultEgx30Watchlist } from "@shared/universe";
import { toast } from "sonner";

const defaultStocks = defaultEgx30Watchlist;

export default function Settings() {
  const query = trpc.settings.get.useQuery();
  const save = trpc.settings.save.useMutation({ onSuccess: () => { toast.success("Settings saved"); query.refetch(); }, onError: error => toast.error(error.message) });
  const schedule = trpc.settings.enableDailySchedule.useMutation({ onSuccess: () => { toast.success("Daily schedule enabled"); query.refetch(); }, onError: error => toast.error(error.message) });
  const [apiKey, setApiKey] = useState("");
  const [showKey, setShowKey] = useState(false);
  const [watchlistText, setWatchlistText] = useState(defaultStocks.join(", "));
  useEffect(() => { if (query.data?.watchlist?.length) setWatchlistText(query.data.watchlist.join(", ")); }, [query.data]);
  const tracked = watchlistText.split(",").map(s => s.trim().toUpperCase()).filter(Boolean);
  return <DashboardLayout><div className="min-h-screen bg-[#071018] text-slate-100 -m-4 p-5 lg:p-8"><div className="mx-auto max-w-5xl"><header className="border-b border-white/10 pb-7"><div className="mb-5 flex items-center gap-3 text-xs font-medium uppercase tracking-[0.24em] text-cyan-300"><KeyRound className="h-4 w-4" /> Workspace configuration</div><div className="flex flex-wrap items-end justify-between gap-5"><div><h1 className="text-3xl font-semibold tracking-tight text-white lg:text-4xl">Settings</h1><p className="mt-3 max-w-xl text-sm leading-6 text-slate-400">Connect your market-data provider and define the instruments that should be analyzed after each close.</p></div><Link href="/" className="text-sm text-slate-400 hover:text-white">← Back to overview</Link></div></header>
{query.isError && <div className="mb-5 rounded-xl border border-rose-300/20 bg-rose-300/[0.06] p-4 text-sm text-rose-200">Unable to load provider settings. Please refresh and try again.</div>}
<section className="grid gap-5 py-7 lg:grid-cols-[1.15fr_.85fr]"><Card className="border-white/10 bg-white/[0.035] text-white"><CardHeader><CardTitle className="flex items-center gap-3 text-base"><KeyRound className="h-5 w-5 text-cyan-300" />Data provider</CardTitle><p className="text-xs leading-5 text-slate-500">The key is encrypted before it is stored and is never shown in full after saving.</p></CardHeader><CardContent className="space-y-6"><div><Label htmlFor="provider" className="text-xs text-slate-400">Provider</Label><Input id="provider" value="EODHD" readOnly className="mt-2 border-white/10 bg-black/20 text-slate-300" /></div><div><Label htmlFor="apiKey" className="text-xs text-slate-400">API key</Label><div className="relative mt-2"><Input id="apiKey" type={showKey ? "text" : "password"} value={apiKey} onChange={e => setApiKey(e.target.value)} placeholder={query.data?.hasApiKey ? "Saved key — enter a new one to replace it" : "Paste your EODHD API key"} className="border-white/10 bg-black/20 pr-11 text-slate-100 placeholder:text-slate-600" /><button type="button" onClick={() => setShowKey(v => !v)} className="absolute right-3 top-1/2 -translate-y-1/2 text-slate-500 hover:text-slate-200" aria-label="Toggle API key visibility">{showKey ? <EyeOff className="h-4 w-4" /> : <Eye className="h-4 w-4" />}</button></div></div><div className="flex items-start gap-3 rounded-xl border border-emerald-300/15 bg-emerald-300/[0.06] p-4 text-xs leading-5 text-emerald-100/70"><ShieldCheck className="mt-0.5 h-4 w-4 shrink-0 text-emerald-300" /><span>Use a key with permission to access EGX end-of-day history. The application only runs after the market-close schedule and does not place orders.</span></div></CardContent></Card>
<Card className="border-white/10 bg-white/[0.035] text-white"><CardHeader><CardTitle className="flex items-center gap-3 text-base"><Clock3 className="h-5 w-5 text-violet-300" />Daily update</CardTitle><p className="text-xs leading-5 text-slate-500">Automated analysis configuration</p></CardHeader><CardContent className="space-y-4"><div className="rounded-xl border border-white/10 bg-black/10 p-5"><p className="text-xs uppercase tracking-[0.18em] text-slate-500">Next cadence</p><p className="mt-3 text-2xl font-semibold text-white">14:30 <span className="text-sm font-normal text-slate-500">Cairo time</span></p><p className="mt-2 text-xs leading-5 text-slate-500">Weekdays after the Egyptian market close.</p></div><div className="space-y-2 text-sm text-slate-300"><div className="flex items-center gap-2"><span className={`h-2 w-2 rounded-full ${query.data?.lastRunStatus === "success" ? "bg-emerald-300" : query.data?.lastRunStatus === "failed" ? "bg-rose-300" : query.data?.hasApiKey ? "bg-cyan-300" : "bg-amber-300"}`} />{query.isLoading ? "Loading status…" : !query.data?.hasApiKey ? "Waiting for source key" : query.data?.lastRunStatus === "failed" ? "Last sync failed" : query.data?.lastRunStatus === "success" ? "Last sync succeeded" : "Provider key saved — awaiting first run"}</div>{query.data?.lastSuccessfulRunAt && <p className="pl-4 text-xs text-slate-500">Last success: {new Date(query.data.lastSuccessfulRunAt).toLocaleString()}</p>}{query.data?.lastRunError && <p className="pl-4 text-xs leading-5 text-rose-300/80">{query.data.lastRunError}</p>}</div><Button onClick={() => schedule.mutate()} disabled={schedule.isPending || Boolean(query.data?.scheduleTaskUid)} variant="outline" className="w-full border-white/10 bg-white/[0.04] text-slate-200 hover:bg-white/[0.08]">{query.data?.scheduleTaskUid ? "Daily schedule active" : schedule.isPending ? "Enabling…" : "Enable daily schedule"}</Button></CardContent></Card></section>
<Card className="border-white/10 bg-white/[0.035] text-white"><CardHeader><CardTitle className="flex items-center gap-3 text-base"><Sparkles className="h-5 w-5 text-amber-300" />Tracked instruments</CardTitle><p className="text-xs leading-5 text-slate-500">Enter EODHD symbols separated by commas. The default list is a starter watchlist; adjust it to your preferred EGX30 coverage.</p></CardHeader><CardContent><textarea value={watchlistText} onChange={e => setWatchlistText(e.target.value)} rows={4} className="w-full resize-none rounded-xl border border-white/10 bg-black/20 p-4 font-mono text-sm leading-7 text-slate-200 outline-none transition focus:border-cyan-300/50" /><div className="mt-4 flex flex-wrap gap-2">{tracked.map(symbol => <Badge key={symbol} className="border-white/10 bg-white/[0.06] font-mono text-xs text-slate-300"><Check className="mr-1 h-3 w-3 text-cyan-300" />{symbol}</Badge>)}</div></CardContent></Card>
<div className="mt-5 flex items-center justify-between gap-4"><p className="max-w-xl text-xs leading-5 text-slate-500">Analytical outputs are not an investment recommendation. Verify data quality and conduct independent research before making decisions.</p><Button onClick={() => save.mutate({ apiKey: apiKey || undefined, dataProvider: "eodhd", watchlist: tracked })} disabled={save.isPending || tracked.length === 0} className="bg-cyan-300 text-slate-950 hover:bg-cyan-200"><Save className="mr-2 h-4 w-4" />{save.isPending ? "Saving…" : "Save settings"}</Button></div></div></div></DashboardLayout>
}
